services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rpl-skandakra-bot:latest
    container_name: rpl-skandakra-bot
    restart: always
    deploy:
      resources:
        limits:
          memory: 128m
