name: Build & Deploy

on:
  workflow_dispatch: # Trigger the workflow manually
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: rpl-skandakra-bot

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create .env file
        run: |
          echo "# Bot credentials" > .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "BOT_ID=${{ vars.BOT_ID }}" >> .env
          echo -e "\n# Server id" >> .env
          echo "SERVER_ID=${{ vars.SERVER_ID }}" >> .env
          echo -e "\n# List channels" >> .env
          echo "CH_INTRO_ID=${{ vars.CH_INTRO_ID }}" >> .env
          echo "CH_LEAVE_ID=${{ vars.CH_LEAVE_ID }}" >> .env
          echo "CH_LOBBY_ID=${{ vars.CH_LOBBY_ID }}" >> .env
          echo "CH_LOG_ID=${{ vars.CH_LOG_ID }}" >> .env
          echo "CH_ROLE_ID=${{ vars.CH_ROLE_ID }}" >> .env
          echo "CH_RULES_ID=${{ vars.CH_RULES_ID }}" >> .env
          echo -e "\n# List roles" >> .env
          echo "ROLE_ADMIN_ID=${{ vars.ROLE_ADMIN_ID }}" >> .env
          echo "ROLE_MEMBER_ID=${{ vars.ROLE_MEMBER_ID }}" >> .env

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set up SSH agent for deployment
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Ensure project directory exists on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }} << 'EOF'
            mkdir -p ~/apps/${{ env.APP_NAME }}
            cd ~/apps/${{ env.APP_NAME }}
            if [ ! -d .git ]; then
              git clone ${{ vars.REPO_URL }} .
            fi
          EOF

      - name: Copy .env file to VPS
        run: |
          scp -o StrictHostKeyChecking=no .env ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }}:~/apps/${{ env.APP_NAME }}/

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }} << 'EOF'
            # Navigate to project directory
            cd ~/apps/${{ env.APP_NAME }}

            # Pull repository
            git pull origin main

            # Stop existing containers
            docker compose down || true

            # Start containers with the locally built image
            docker compose up --build -d
          EOF
